✨ feat: RSS 등록 승인 혹은 거부 시 신청자 메일로 알림 전송
boostcampwm-2024/web05-Denamu pull request #114
Opened 2024-11-18 16:31 UTC by CodeVac513

# 🔨 테스크

### Issue

-   close #113

# 📋 작업 내용

-   RSS 등록 신청자에게 심사 결과를 전송할 수 있도록 EmailModule과 EmailService를 구현했습니다.
- 해당 과정에서 RSS 등록 거부 후 신청자 email 정보가 필요하여 삭제 로직을 수정했습니다.
  - 먼저 해당하는 RSS 엔티티를 찾고 그 후에 삭제할 수 있도록 수정했습니다. 
- 마지막으로 이메일 전송에 필요한 계정과 패스워드를 github secrets에 등록하여 환경 변수로 저장할 수 있도록 workflow를 수정했습니다.

# 📷 스크린 샷

![image](https://github.com/user-attachments/assets/ba86ac81-0915-4cd5-8840-955123a7927c)
- 2개의 로우가 출력되는 부분은 승인 혹은 거부하기 전 상태입니다.
- 승인 혹은 거부가 성공적으로 수행되면 아래 결과와 같이 로우가 모두 삭제됩니다.
  

![image](https://github.com/user-attachments/assets/499a9e41-6ed5-4d7c-8728-7e8344194d89)
- 승인 시 발송되는 메일입니다.

![image](https://github.com/user-attachments/assets/0352dd48-f440-47c1-9a34-1186af17e831)
- 거부 시 발송되는 메일입니다.

![image](https://github.com/user-attachments/assets/d6508980-4801-4c72-b505-591c7d7ad6cf)
- 없는 RSS 등록을 대상으로 승인이나 거부를 수행하면 위와 같이 예외 메세지가 전송됩니다.

2024-11-18 17:17 UTC, Jo-Minseok requested changes
고생하셨습니다! 코드 가독성과 관련한 피드백 위주로 작성해봤습니다. 필요하신 부분은 반영해주시면 좋겠습니다! 덕분에 메일 모듈에 대해 알게 되었습니다.

2024-11-18 17:17 UTC, Jo-Minseok commented on server/package.json
> +    "@nestjs/common": "^10.4.7",
P3) 엇..? 모든 라이브러리들 버전이 갑자기 올라갔는데 혹시 이유가 있으신가요? 사용 방법 바뀐 건 없는 지 확인하고 업데이트 하신걸까요?

2024-11-18 17:17 UTC, Jo-Minseok commented on server/src/common/email/email.service.ts
> +  async sendMail(to: string, clientName: string, successFlag: boolean = true) {
P3) Default Value를 넣으신 이유가 있으신가요? Default Value가 있으면 코드를 읽을 때, 가독성을 많이 해친다고 생각합니다. 이 코드를 쓴 사람 외에는 처음 읽을 때 이게 왜 있지? 라는 의문을 가지게 되고, 사용할 때, 어떤 곳에는 값이 없고 어떤 곳에는 false가 있으면 통일되지 않은 느낌이 들 것 같네요...! 취향 차이라 이럴 수도 있다고 알아주시면 감사하겠습니다.

2024-11-18 17:17 UTC, Jo-Minseok commented on server/src/rss/rss.service.ts
> +    await this.emailService.sendMail(rss.email, rss.userName);
P2) 위 작업들을 하나의 트랜잭션으로 묶고, this.emailService.sendMail을 Promise.all로 처리하면 더 빠르지 않을까 싶네요. await이 3번이나 연속으로 나오면 불필요한 Blocking이 생긴다고 생각합니다.

2024-11-18 17:17 UTC, Jo-Minseok commented on server/src/rss/rss.service.ts
> +      where: { id: id },
P5) where: { id: id} -> where : { id } 로 쓰는 게 깔끔할 것 같기도 하네요

2024-11-18 17:17 UTC, Jo-Minseok commented on server/src/common/email/email.service.ts
> +      const subject = `RSS 등록이 승인되었습니다.`;
P3) 취향 차이일 수 있는데, if 문 안에서 const로 if 외부와 똑같은 변수 선언을 하는 것 보다는 위에서 let으로 선언하고 대입하여 사용하는 건 어떠신가요? 그럼 변수명 틀릴 일이 없으니 더 안전할 것 같다는 느낌이 드네요.
```
let subject, content;
if(successFlag){
    subject = `RSS 등록이 승인되었습니다.`;
    content = `~`;
    return { subject, content };
}
subject = `RSS 등록이 거부 되었습니다.`
content = `~`;
return { subject, content };
```
이런식으로 하면 밑에서 변수 명을 다르게 적을 위험성이 줄어듭니다.
아니면
```
const result = successFlag ? '승인':'거부';
return {
    subject: `RSS 등록이 ${result}되었습니다.`;
    content: `${clientName}님의 RSS 등록이 ${result}되었습니다.`;
}
```
이런 식으로도 줄일 수 있을 것 같네요.

2024-11-19 02:37 UTC, CodeVac513 commented on server/package.json
> +    "@nestjs/common": "^10.4.7",
100% 확실한 건 아닌데, 저번에 모듈 설치했다가 취약점 엄청 많이 나왔던 사진 기억하시나요? 그 때 취약점 해결하려다가 자동으로 업데이트된 것 같아요.
다 수정해서 반영해놓겠습니다.

2024-11-19 02:39 UTC, CodeVac513 commented on server/src/rss/rss.service.ts
> +      where: { id: id },
위 코드도 id라고 작성되어 있어서 이렇게 했는데, 차라리 둘 모두 수정해서 올리겠습니다.

2024-11-19 02:43 UTC, CodeVac513 commented on server/src/common/email/email.service.ts
> +      const subject = `RSS 등록이 승인되었습니다.`;
아래 방법 너무 좋네요.
템플릿 하나 정해두고 문장만 삼항 연산으로 바꿀 수 있어서 아래 방법이 좋을 것 같습니다. 
왜 삼항 연산 생각이 잘 안날까요? :(

2024-11-19 02:46 UTC, CodeVac513 commented on server/src/rss/rss.service.ts
> +    await this.emailService.sendMail(rss.email, rss.userName);
반영하겠습니다 👍

2024-11-19 03:12 UTC, CodeVac513 commented on server/src/common/email/email.service.ts
> +  async sendMail(to: string, clientName: string, successFlag: boolean = true) {
이름부터 `success`가 아니라 `approve`로 했어야 했네요.
승인/거부 판별을 위해 설정한 값이고 기본적으로 승인이 많을거라 생각해서 true를 디폴트로 줬습니다. 불리언 값이라 true/false 2가지만 있기도 하고요.
그래도 헷갈릴 여지를 남기는 건 좋지 않으니 수정하도록 하겠습니다.

2024-11-19 05:29 UTC, asn6878 requested changes
고생하셨습니다 👍 
Prettier 설정이랑, 응답속도 확인 부탁드립니다!

2024-11-19 05:29 UTC, asn6878 commented on server/src/rss/rss.service.ts
>      });
P2: 제 환경에서는 prettier가 줄바꿈을 강제하는데, 무성님은 혹시 prettier 설정을 안해두고 사용하시나요? 🥶
개발 환경에 prettier 설정이 다르면 계속 이렇게 서로 의미없는 줄바꿈 이력이 반복될까 싶어 우려스럽습니다.

2024-11-19 05:29 UTC, asn6878 commented on server/src/rss/rss.service.ts
>  }
P4: 제가 예전에 비슷한 기능을 개발할때 신경썼던 부분이 생각나 공유해봅니다. (사실 엄청 중요한건 아니에요. 한번 해보고싶으시면 시도해보셔도 좋아요.)

`메일의 전송` <-> `DB 작업이 성공적으로 완수됨` 두가지 작업은 마치 하나의 트랜잭션 처럼 원자성을 보장하는게 조금 더 안전합니다.

DB에 문제가 생겨 RSS가 실제로 승인처리는 안되었는데? 사용자에게는 승인이 되었다는 메일이 가게 될테니까 말이에요. 이를 위해서 저는 예전에 이벤트방식을 통해 처리했습니다 만...

js에서는 단순히 Promise.all 구문에서 `sendMail` 메소드만 빼서 따로 진행해줘도 괜찮을 것 같네요.

2024-11-19 05:29 UTC, asn6878 commented on server/src/rss/rss.service.ts
> +    ]);
P2: 이렇게 해두면 rss.controller에서 await 키워드로 rss.service의 해당 메서드를 호출 중이므로 메일이 실제로 발송될때까지 http 응답이 안오지 않나요? 확인 부탁드립니다.

2024-11-19 05:45 UTC, CodeVac513 commented on server/src/rss/rss.service.ts
>      });
prettier 사용하고 있습니다. 저기 고쳐진 부분은 `{ id: id }` -> `{ id }`로 고쳐서 잡아주는 것 아닌가요?

2024-11-19 05:47 UTC, Jo-Minseok commented on server/src/rss/rss.service.ts
> +    await this.emailService.sendMail(rss.email, rss.userName);
P5) Promise.all로 묶으면 DB에서 처리 안 됐는데 메일이 갈 수도 있겠네요...?

2024-11-19 05:48 UTC, CodeVac513 commented on server/src/rss/rss.service.ts
> +    ]);
바로 반영하겠습니다. 비동기 작성하다가 '인수에서 email이나 useName은 이행된 값을 받아야하지 않나?' 하면서 헷갈린 것 같아요.

2024-11-19 05:48 UTC, asn6878 commented on server/src/rss/rss.service.ts
>      });
아뇨, 제 환경에서는
```javascript
      where: {
        id
      },
```
이렇게 바뀝니다. 제가 뭔가 설정이 잘못되어있나요?? (프리티어 잘모름)

2024-11-19 06:57 UTC, CodeVac513 commented on server/src/rss/rss.service.ts
>  }
메일 전송과 DB 작업에서 원자성을 보존한다는 게 가벼운 일은 아니었네요. 
일단은 구현해놓고 주말이나 금요일에 시간이 좀 남을 때 더 고민해봐야겠습니다. 
좋은 의견 감사합니다.

2024-11-19 07:04 UTC, CodeVac513 commented on server/src/rss/rss.service.ts
> +    await this.emailService.sendMail(rss.email, rss.userName);
DB만 Promise.all로 묶고 sendmail은 밖으로 뺐습니다.
sendmail은 비동기적으로 동작할 수 있도록 await도 빼버렸습니다.

2024-11-19 07:10 UTC, CodeVac513 commented on server/src/rss/rss.service.ts
> +    ]);
해당 부분 수정하고 실수로 Feed fix PR에 올려버렸습니다. 죄송합니다. ㅠㅠ

2024-11-19 12:25 UTC, Jo-Minseok approved these changes
피드백이 꽤 많았을텐데 적용하시느라 고생 많으셨습니다!

2024-11-19 13:00 UTC, CodeVac513 commented on server/src/rss/rss.service.ts
>      });
위 사항은 게더에서 해결했습니다.

2024-11-20 01:35 UTC, asn6878 commented on server/src/rss/rss.service.ts
> +    ]);
확인했습니다~

2024-11-20 01:36 UTC, asn6878 approved these changes
피드백 반영해주셔서 감사합니다 🚀 
고생하셨어요!

2024-11-20 01:38 UTC, merged