🐛 fix: feed 요청 시 author 프로퍼티가 추가되도록 수정
boostcampwm-2024/web05-Denamu pull request #116
Opened 2024-11-19 05:22 UTC by CodeVac513

# 📋 작업 내용

- Feed 데이터를 조회한 뒤 응답하는 과정에서 JOIN이 제대로 이루어지지 않음을 확인했습니다.
- 데이터 조회 후 author 프로퍼티가 추가되어 반환될 수 있도록 코드를 수정했습니다.

# 📷 스크린 샷
![image](https://github.com/user-attachments/assets/f3bcf7dc-5dcc-45e5-bfb1-c76d7b945945)

2024-11-19 12:29 UTC, Jo-Minseok requested changes
고생하셨습니다! 이상한 부분 체크해뒀으니 확인 부탁드립니다.

2024-11-19 12:29 UTC, Jo-Minseok commented on server/src/feed/feed.repository.ts
> +import { QueryFeedDto } from './dto/query-feed.dto';
P2) 얘는 뭔가요? 갑자기 밑에 줄에서 import...?

2024-11-19 12:29 UTC, Jo-Minseok commented on server/src/feed/feed.repository.ts
> +      where: whereCondition,
P3) 이정도는 변수 선언 말고 그냥 대입하는 걸 추천드립니다. 엄청 긴 조건 문이 아니라서 내부에 포함되어도 괜찮다고 봅니다.

2024-11-19 15:59 UTC, CodeVac513 commented on server/src/feed/feed.repository.ts
> +      where: whereCondition,
반영했습니다!

2024-11-20 04:11 UTC, asn6878 approved these changes
이전에 구두로 확인한 부분 포함해 확인했습니다.

고생하셨어요~

2024-11-20 04:59 UTC, Jo-Minseok approved these changes

2024-11-20 05:00 UTC, merged