✨ feat: 조회수 업데이트 API 구현
boostcampwm-2024/web05-Denamu pull request #138
Opened 2024-11-20 09:42 UTC by CodeVac513

### Issue

-   close #20

## 비로그인 사용자에 대해 조회수를 어떻게 올릴 것인가?
### 쿠키를 발행하고 쿠키가 없는 사용자에 한해서 IP 검사를 실시한다.
1. 쿠키에 피드 ID를 저장하고 Redis에 IP를 저장하는 set을 운영하여 검사한다.
- 장점: 서버에서는 IP만 저장하고 있으면 되어서 쿠키 정보를 저장할 필요가 없습니다.
- 단점: 피드를 100개 봤다면 100개의 쿠키가 클라이언트의 PC에 저장됩니다.

2. 쿠키에 세션 ID와 같이 사용자를 특정할 수 있는 값을 키로 가지는 과 IP를 저장하는 set을 Redis에 저장한다.
- 장점: 클라이언트 한 명에 대한 UUID를 생성하고 거기에 봤던 피드를 저장하여 쿠키의 개수가 1개면 충분합니다.
- 단점: Redis에서 정보를 관리하기에 자주 접근하게 됩니다. 그리고 서버에서 관리할 데이터가 늘어납니다.

#### 결과
- 쿠키에 피드 ID를 저장하고 Redis에는 IP를 저장하는 set만 운영하는 것으로 결정되었습니다.
- 처음 이 주제에 대해 논의했을 때, 1번 방법으로 결정되었으나 제가 구현하다보니 사용자에게 피드 개수만큼의 쿠키가 생성되는 게 어색하여 2번 방법을 생각했습니다.  
팀원들과 소통한 결과, UUID 생성하는 시점에 대한 고민이나 관리할 데이터가 늘어남, Redis에 자주 접근한다는 것 등을 고려해서 1번 방법이 결정되었습니다.

# 📋 작업 내용

- 쿠키와 IP를 활용한 조회수 증가 API 구현
- 자정이 지나면 IP 정보를 Redis에서 삭제

# 📷 스크린 샷
- 응답을 받고 쿠키 확인을 하면 아래와 같습니다.
- 쿠키의 만료 시간은 다음 날 자정입니다.
![image](https://github.com/user-attachments/assets/7ea610b4-7be1-4a53-90d0-f9c768a31bb9)

- MySQL의 feed 테이블에서 해당 로우의 view_count가 업데이트됩니다.
![image](https://github.com/user-attachments/assets/07683f11-fba5-4d63-b151-eba01645ef27)

- IP가 등록되어 조회수를 올릴 수 없도록 설정됩니다.   
   (해당 IP는 제가 임의로 설정했으며 실제 사용되는 값은 클라이언트의 IP입니다.)
![image](https://github.com/user-attachments/assets/f4ba0f73-d438-4ed9-b8c8-36ddb76df6a4)

2024-11-20 12:48 UTC, Jo-Minseok requested changes
고생하셨습니다! 코드 잘 적으신 것 같습니다! 리뷰 하나 작성해뒀으니 고려해주세용~

2024-11-20 13:29 UTC, asn6878 commented on server/src/feed/feed.controller.ts
> +    const ip = request.headers[`CF-Connecting-IP`];
3항연산자 써서 `CF-Connecting-IP' 가 존재할때만 그걸로 하고, 없으면 request에서 다이렉트로 추출하면 되지 않을까요?

2024-11-21 01:04 UTC, Jo-Minseok approved these changes

2024-11-21 01:49 UTC, asn6878 approved these changes
사소한 의견 및 질문 남겨두었습니다.
고생하셨어요~~

2024-11-21 01:49 UTC, asn6878 commented on server/src/feed/feed.service.ts
> +  }
P5: expires랑 maxAge랑 무슨차이 인가요? 이전에 미션할때 저는 maxAge를 썼던것으로 기억해서 여쭤봅니다!

2024-11-21 01:49 UTC, asn6878 commented on server/src/feed/feed.service.ts
> +
P4: 160번 라인과 동일하게, Redis 키값과 같은 문자열값들은 상수화 해도 좋을 것 같다는 의견입니다~

2024-11-21 02:34 UTC, CodeVac513 commented on server/src/feed/feed.service.ts
> +  }
maxAge는 몇초인지 계산해서 만료가 되고 expires는 만료 날짜가 정해져서 그 시간이 되면 삭제됩니다.
만약 maxAge를 사용한다면 지금처럼 다음날 자정을 설정해주는 게 아니라 
현재 시간에서 자정까지 몇 초가 남았는지 계산해서 넣어주게 될 것 같아요.

2024-11-21 02:36 UTC, CodeVac513 commented on server/src/feed/feed.service.ts
> +
따로 상수 파일로 뽑아서 사용한다는 뜻일까요?
아니면 서비스 내부에서 필드로 두고 사용한다는 뜻일까요?

2024-11-21 03:06 UTC, asn6878 commented on server/src/feed/feed.service.ts
> +
저는 그냥 해당 서비스 파일 내에서 전역적으로 선언해서 썼는데, 방법은 상관없다고 봐요!

2024-11-21 04:27 UTC, CodeVac513 commented on server/src/feed/feed.service.ts
> +
common/redis 하위에 redis.constant.ts라는 파일을 하나 만들어서 key값을 저장하는 JSON을 하나 생성했습니다. 거기서 불러다가 사용하는 방식으로 수정했어요.

2024-11-21 04:31 UTC, merged