✨ feat: rss 등록 거절 조회 API 및 트랜잭션 적용
boostcampwm-2024/web05-Denamu pull request #186
Opened 2024-11-23 18:16 UTC by Jo-Minseok

# 🔨 테스크

### Issue

-   close #154

### PR 분리
- 본 브랜치에서 이메일에 description을 담아서 이메일을 전송하는 기능은 적합하지 않다고 판단했다.
- 해당 브랜치에서 새로운 브랜치를 분기하여 새로운 작업을 시작하여 PR을 작성해야겠다.

### Promise.all이 올바른 방식일까?

-   무성님께서 DB 트랜잭션을 구현하실 때, Promise.all을 이용하여 DB에 적용하게 했다. 하지만 이 방식이 코드를 리뷰 다 하고 병합되고 나서 잘 못된 방법인걸 깨닳았다. 트랜잭션은 DB 수행 시 실패했을 경우 작업을 Rollback 해야 하는데, 우리 코드에서는 데이터가 소실만 되거나 데이터가 저장만 될 수 있었다. 그래서 이 버그를 수정했다.

# 📋 작업 내용

-   RSS Reject 테이블 생성
- Rss Accept History API 구현
- RSS Reject History API 구현
- 진짜 트랜잭션화
- RSS Reject시 description을 입력받도록 변경

# 📷 스크린 샷(선택 사항)

동작 화면 첨부

2024-11-24 05:49 UTC, CodeVac513 reviewed
이메일 관련해서 하나 남겨놨습니다.
수고많으셨어요!

2024-11-24 05:49 UTC, CodeVac513 commented on server/src/rss/rss.service.ts
>      this.emailService.sendMail(rss.email, rss.userName, true);
P3) 이거 트랜잭션 결과에 상관없이 이메일이 발송되는 문제도 있을 것 같네요.
DTO에서 데이터 형식에 관한 검증은 하지만 삽입 중에 연결이 끊어진다던가 그런 문제가 발생할 수는 있겠네요.
그럴 때도 이메일이 그대로 발송될 것 같습니다.
(그게 맞다면 처음에 저도 이상하게 동작하는 코드를 작성했군요...)

2024-11-24 05:51 UTC, CodeVac513 approved these changes

2024-11-24 05:51 UTC, Jo-Minseok commented on server/src/rss/rss.service.ts
>      this.emailService.sendMail(rss.email, rss.userName, true);
혹시 예외 처리를 하셨으면 하는 걸까요?-?

2024-11-24 06:10 UTC, CodeVac513 commented on server/src/rss/rss.service.ts
>      this.emailService.sendMail(rss.email, rss.userName, true);
-게더에서 해결 완료-

2024-11-25 05:13 UTC, asn6878 requested changes
이야기 해볼만한 사안이 있는것 같아 코멘트 남겨두었습니다.
이외에는 이견 없습니다 :)

2024-11-25 05:13 UTC, asn6878 commented on server/src/rss/rss.entity.ts
> +}
P1: 이전에 한번 이야기 나눴던 주제로 기억하는데 기억이 가물가물 하네요 😅 
저희는 기존에 엔티티(테이블 이름)를 중심으로 디렉토리를 구분했어요. 하지만 **지금은 이 엔티티 중심설계의 일관성이 깨진 것 같습니다.**

**현재 `rss` 디렉토리 안에 `rss_reject`에 대한 선언이 함께 포함되어 있습니다.** 
저희가 하나의 테이블 내에서 특정 필드로 구분하는 방법을 택하지 않고, 테이블을 아예 분리하자! 라는 쪽으로 가서 이런 문제가 발생한 듯 합니다. (테이블을 분리해서 얻는 득은 있긴 합니다. 각종 nullable 필드를 사용하지 않아도 되고, 그만큼 중복 데이터가 줄어들긴 하니까요.)

두가지 방법이 있을것 같은데요.
- `blog` 테이블을 `rss_accept`로 변경 후 `rss.entity.ts`에 함께 선언하고, 비즈니스 로직 역시 해당 디렉토리 아래로 합치기.
- 마찬가지로 `blog` 테이블을 `rss_accept`로 변경 후 `rss_reject`, `rss_accept`, `rss` 도메인을 분리하고 각각의 컨트롤러, 서비스로 분리하기.

저는 두 방식 다 어느정도 장단점이 있다고 생각하는데, @Jo-Minseok @CodeVac513 두분 생각은 어떠세요?

2024-11-25 05:15 UTC, Jo-Minseok commented on server/src/rss/rss.entity.ts
> +}
저는 전자를 더 선호합니다.

2024-11-25 05:30 UTC, CodeVac513 commented on server/src/rss/rss.entity.ts
> +}
2안을 선택하면 너무 복잡해질 것 같아서 전자가 나을 것 같습니다. 저는 1안으로 가져가는 게 나을 것 같아요.

2024-11-25 05:32 UTC, asn6878 commented on server/src/rss/rss.entity.ts
> +}
좋아요! 저도 2안은 디렉토리를 분리할 만큼 각 도메인 로직들이 별로 안 복잡할 것 같아서, 1안으로 가는걸로 하시죠!

2024-11-25 17:30 UTC, Jo-Minseok commented
@asn6878 피드백 부분 적용했습니다!

2024-11-25 18:11 UTC, asn6878 approved these changes
코드 전체를 한줄씩 읽은 PR은 이게 처음이네요
이것이야 말로 테스트의 중요성이 아닐까... 라는 생각이 드는 하루입니다ㅋㅋㅋㅋㅋㅋㅋ
피드백 반영해주셔서 감사합니다. 고생많으셨어요 👍

2024-11-26 01:29 UTC, merged