⚡️ perf: 서버 안정성 향상을 위한 채팅 서버 최대 사용자 제한 추가
boostcampwm-2024/web05-Denamu pull request #198
Opened 2024-11-25 13:38 UTC by asn6878

# 🔨 테스크
### Issue
-   close #195 

# 📋 작업 내용

- 웹소켓 채팅서버 최대 커넥션 수 제한
[4주차 스프린트 리뷰회의](https://balsam-barometer-716.notion.site/Week-4-09a81378938f43399603575ec409f506?pvs=4)에서 발의된 안건을 반영하기 위해 웹소켓 서버에서 `handleConnection` 을 수행할 때 서버의 커넥션 수를 확인하고, 500명 이상이면 아래와 같은 이벤트를 connection을 요청한 클라이언트에게 반환합니다.

`error`, `message: '채팅 서버의 한계에 도달했습니다. 잠시후 재시도 해주세요.'`

2024-11-25 16:52 UTC, CodeVac513 approved these changes
수고 많으셨습니다!
P5) 질문이 하나 있는데요,
지금 Nest 프로세스가 2개 동작하고 있으니 채팅방은 각각 서버에 한 개씩 500명해서 총 1000명 제한이 걸려있는게 맞나요?

2024-11-25 17:53 UTC, Jo-Minseok requested changes
고생하셨습니다! 한 가지 고려해볼 사안 작성해뒀습니다.
@CodeVac513 답변 대신 드리자면 지금 당장에는 저희 프로세스 하나로 가자는 이야기로 저번 주에 나왔었습니다. 나중에 서버 사양 보고 교체하는 식으로 넘어 가야할 것 같습니다. 그리고 웹 소켓이 생각보다 무거워서 가능하다면 채팅 서버만 따로 분리할듯 합니다.

2024-11-25 17:53 UTC, Jo-Minseok commented on server/src/chat/chat.gateway.ts
> +    const userCount = this.server.sockets.sockets.size;
P3) 확실한 표기를 위해서 this.server.engine.clientsCount 를 사용하는 건 어떠신가요? 이 변수가 엔진 레벨에 직접 접근 할 수 있어서 더 빠르다고 합니다. 단순 연결 클랑이너트 수만 확인하면 되기에 별도의 소켓 ID에 대해서 몰라도 된다네요. 결국 연결된 소켓들의 Map이냐, 단순 숫자 값이냐의 차이라고 따지면 단순 숫자가 낫다고 생각합니다.

2024-11-26 07:36 UTC, Jo-Minseok approved these changes

2024-11-26 08:34 UTC, merged