✨ feat: rSS 등록 승인 시 RSS URL을 분석하여 블로그 플랫폼을 등록하는 로직 추가
boostcampwm-2024/web05-Denamu pull request #208
Opened 2024-11-26 03:54 UTC by CodeVac513

# 🔨 테스크
### Issue

-   close #201

# 📋 작업 내용

- 오브젝트 스토리지를 생성하고 블로그 로고 이미지를 SVG파일로 업로드했습니다.
- 위 데이터를 프론트에서 활용할 수 있도록 RSS URL을 보고 어느 블로그 플랫폼인지 식별하는 로직을 추가했습니다.
  - 현재는 회의에서 결정난대로 Medium, Github, Velog, Tistory만 지원하며 이외의 블로그는 etc로 분류됩니다.
- 위 데이터를 Feed에서 Join 연산 했을 때도 활용할 수 있도록 Feed 도메인의 코드를 수정했습니다.

# 📷 스크린 샷
- 아래는 로컬 환경에서 동작 결과와 업데이트된 Swagger API 명세를 확인한 스크린 샷입니다.
![승인 후 accept_rss 테이블](https://github.com/user-attachments/assets/8b5bfe0e-8746-48a2-99c6-6a8841af3d1a)

![피드 조회 시 블로그 플랫폼이 함께 전송될 수 있도록](https://github.com/user-attachments/assets/1df320bc-cd6d-4b7d-8b6e-6a5b0c679c75)

![image](https://github.com/user-attachments/assets/285a8a27-a479-4393-96d6-ca5652042a1e)

![image](https://github.com/user-attachments/assets/b8145067-0976-45cf-a857-59fd4d537182)

2024-11-26 07:35 UTC, Jo-Minseok requested changes
고생하셨습니다! 정말 사소한 코드 일관성에 관련된 리뷰 작성해뒀으니 검토 부탁드립니다.

2024-11-26 07:35 UTC, Jo-Minseok commented on server/src/rss/rss.entity.ts
> +    blog.blogPlatform = blogPlatform;
P3) feeds 는 관계다 보니 속성이 들어올 거면 관계 위에 들어오는 게 일관성 있을 것 같습니다.

2024-11-27 02:14 UTC, asn6878 approved these changes
확인했습니다!
고생하셨어요 :) 👍

2024-11-27 02:40 UTC, CodeVac513 commented on server/src/rss/rss.entity.ts
> +    blog.blogPlatform = blogPlatform;
반영 완료 했습니다!

2024-11-27 02:42 UTC, Jo-Minseok approved these changes
고생하셨습니다!

2024-11-27 02:51 UTC, merged