✨ feat: 금일 게시글 조회수 통계 API 구현
boostcampwm-2024/web05-Denamu pull request #214
Opened 2024-11-26 10:07 UTC by Jo-Minseok

# 🔨 테스크

### Issue

-   close #162

### 테스트 픽스처 설정
- 매 테스트 코드에서 moduleFixture와 app을 초기화하는 건 비효율적이라 생각했다.
- Cookie 사용 같은 옵션이나 API Prefix를 매번 적다보면 놓칠 수 있고 매번 중복 코드를 작성해야 하는 문제가 있었다.
- E2E 테스트를 하려면 전체 앱 가동 후 테스트를 수행해야 한다고 판단했다.

# 📋 작업 내용

- `/api/statistic/today` Notion API 명세서 작성
-   `/api/statistic/today` API Swagger 구현
- 테스트 픽스처 app, moduleFixture 분리
- `/api/statistic/today` 테스트 코드 작성

# 📷 스크린 샷(선택 사항)

동작 화면 첨부

2024-11-26 16:42 UTC, asn6878 requested changes
테스트 코드 잘 참고 하겠습니다~ 👏 
몇가지 질문 및 변경사항 남겨뒀는데, 확인해주시면 감사하겠습니다 🙇

2024-11-26 16:42 UTC, asn6878 commented on server/src/statistic/statistic.service.ts
> +      redisKeys.FEED_TREND_KEY,
P5: 이거 이런식으로 따로 상수 모아놓고 쓰는데가 있었군요 ㅋㅋㅋ
채팅쪽에는 직접 선언해서 썼는데, 변경해야겠네요 🤔

2024-11-26 16:42 UTC, asn6878 commented on server/src/statistic/statistic.api-docs.ts
> +      },
P2: 저희 최종적으로 예외응답에는 `schema` 안써주기로 했으니, 이제는 제거 해주셔도 될 것 같습니다!

2024-11-26 16:42 UTC, asn6878 commented on server/src/statistic/dto/statistic-query.dto.ts
> +  @IsInt({ message: '정수로 입력해주세요.' })
P3: 이런 정수값 input에 Min을 설정해주어야 했는데, 깜박했네요. (지금 다른곳에서 음수값 넣으면 500 터지는 곳이 꽤 있네요. 리팩토링 할때 이것도 싹 몰아서 처리해야겠네요 👏)

추가적으로, `@Type(() =>  Number)` 보다 이전에 `@Min`이 선언되어있는데, 순서는 상관 없는지 궁금합니다!

2024-11-26 16:42 UTC, asn6878 commented on server/test/statistic/today.e2e-spec.ts
P2: 통합테스트의 파일명이 statistics 가 아니라 today인 이유가 궁금합니다.

제가 이해하기로는 statistics.e2e-spec.ts 내에 `GET api/today`에 대한 describe 함수가 있는게 맞는데, 특별한 의도가 있으셨나요?

2024-11-26 16:44 UTC, Jo-Minseok commented on server/src/statistic/statistic.service.ts
> +      redisKeys.FEED_TREND_KEY,
ㅋㅋㅋ 저도 까먹고 간혹 사용 안 하는데, push하기 전에 생각나서 부랴부랴 적용했습니다.

2024-11-26 16:44 UTC, Jo-Minseok commented on server/src/statistic/statistic.api-docs.ts
> +      },
아 맞네요...! 습관적으로 적어버렸습니다 ㅎ;

2024-11-26 16:46 UTC, Jo-Minseok commented on server/test/statistic/today.e2e-spec.ts
막상 E2E 테스트를 한 파일에 몰아두기에는 너무 길어지고 관리하기가 상당히 어렵다고 느껴졌습니다. 단순 Read API만 봐도 E2E 테스트 코드가 200줄이 되는데, 한 도메인에 API가 많으면 6개가 있는데, 그러면 최소로 코드 수를 잡아도 1200줄이 한 테스트 파일 내에 존재하게 됩니다. 그래서 앞으로 도메인 내에서 라우터 경로로 할까 생각해서 파일 이름을 today로 적었습니다.

2024-11-26 16:50 UTC, Jo-Minseok commented on server/src/statistic/dto/statistic-query.dto.ts
> +  @IsInt({ message: '정수로 입력해주세요.' })
네 상관 없습니다! Min 같은 경우 값이 숫자값일 때만 유효성을 검사합니다. 즉 문자열일 때는 검사를 안 하는 것입니다. 그럼 검사 패스를 하면 IsInt에서 어짜피 걸립니다.

2024-11-26 17:40 UTC, asn6878 commented
> 막상 E2E 테스트를 한 파일에 몰아두기에는 너무 길어지고 관리하기가 상당히 어렵다고 느껴졌습니다. 단순 Read API만 봐도 E2E 테스트 코드가 200줄입니다. 한 도메인에 API가 많으면 6개가 있는데, 그러면 최소로 코드 수를 잡아도 1200줄이 한 테스트 파일 내에 존재하게 됩니다. 그래서 앞으로 도메인 내에서 라우터 경로로 파일명으로 할까 생각해서 파일 이름을 today.e2e-spec.ts로 적었습니다. - @Jo-Minseok 

_생각 정리하다가 글이 좀 길어져서 테스트 컨벤션 자체에 대한 논의로 이어졌네요. @CodeVac513 무성님도 같이 보고 의견 주시면 감사하겠습니다._

저는 조금 다른 의견인게, 이 방법대로 하면 한 도메인에 6개의 API가 있으면 테스트 환경 app을 initialize 하고 실행 후에 close 하는 과정이 6번 일어납니다.
정확하게 아직 저는 이걸 돌려본적이 없어서 모르겠는데, 이러면 통합 테스트 수행시간이 꽤나 상당할 것으로 예상되어 저는 하나의 도메인에 대한 (즉, 하나의 컨트롤러에 대한) 테스트는 한 파일안에서 수행되어야 한다고 생각해요.

**그래서 저는 반대로 '왜 단순 Read API테스트가 200줄이나 되었을까?' 라는 생각을 하며 고민해보았는데요.**

## 문제점
**1. 테스트용 given 데이터가 불필요하게 많음.**
테스트용 데이터셋으로 약 5개의 데이터가 존재했는데, 이 데이터들은 사실상 2번까지만 존재해도 테스트를 하는 목적 자체는 만족할 수 있습니다. 이 불필요한 데이터들을 제거하면 약 50줄 정도를 줄일 수 있었습니다. (본 케이스에서는)

**2. 인풋값 유효성 검사를 분리.**
이전에 저희가 인풋 유효성 검사는 E2E에서 함께 수행하자. 라는 결론을 냈던 것으로 기억이 나는데요!
`실수를 입력한다`, `문자열을 입력한다`, `음수를 입력한다` 와 동일하게 단순히 "`ValidationPipe` 기능이 옳바르게 동작하는가?"를 다시한번 검증하는 것과 다를바가 없다고 생각합니다.

통합 테스트는 비즈니스 로직에 집중하는 것이 중요하다고 생각하는데, ValidationPipe가 의도치 않게 동작 한다는 것은 비즈니스 로직과는 별개로 NestJS 자체적인 문제라고 생각 됩니다.

그렇지만 저희가 ValidationPipe를 올바르게 사용하지 못한 상황에 대한 검증의 필요성은 여전했습니다.
이 부분을 위해서 생각해낸 대안이 `Controller Test` 혹은 `DtoTest` 입니다.

```typescript
// test/statistic/statistic.dto.spec.ts
import { TodayStatisticDto } from '../../../src/statistic/dto/today-statistic.dto';
import { validate } from 'class-validator';

describe('TodayStatisticDto', () => {
  it('정수가 아닌 limit를 거부해야 합니다.', async () => {
    const dto = new TodayStatisticDto();
    dto.limit = 1.1;
    const errors = await validate(dto);
    expect(errors.length).toBe(1);
    expect(errors[0].constraints).toHaveProperty('isInt', '정수로 입력해주세요.');
  });
...
```
위와 같은 형태로 validation과 관련된 유효성 검사들을 app의 실행 없이 구성해두면 저희가 Validation Pipe를 사용하다가 발생하는 오류들은 얼추 검증이 가능 할 것이라고 생각했습니다.

## 결론
위와 같은 방법을 도입하면 `beforeAll` 을 제외하고 순수하게 `GET api/statistic/today` 에서 검증할 코드의 라인수는 50줄 내외라고 생각합니다.

여기에 대한 민석님과 무성님 의견도 듣고싶습니다.

2024-11-26 17:41 UTC, asn6878 approved these changes
이게 코멘트만 따로 달려고 했는데 Request Changes 상태에서는 pending이 되어버리네요 😅

일단 이건 추후에 변경해도 되는 사항이라고 생각해서, Approve 해두겠습니다.

Test와 관련되서 고민을 좀 하면서 든 생각들이 있는데, 의견주시면 감사하겠습니다~

2024-11-26 17:41 UTC, asn6878 commented on server/src/statistic/dto/statistic-query.dto.ts
> +  @IsInt({ message: '정수로 입력해주세요.' })
엇, 그게 아니라 질문 자체는 아직 `limit` 필드의 자료형이 number가 되지 않았는데 `@Min` 이 수행 가능한가? 가 궁금한 점이었어요!

문자열이면 단순히 패스된다면, '-1' 이라는 입력값이 들어왔을때 `@Min`에서 검증하지 못하는게 아닌가? 라는 궁금증이었습니다.

2024-11-26 17:55 UTC, Jo-Minseok commented
@asn6878 app을 initialize를 하고 실행 후 close 하는 과정이 6번 일어난다고 하셨는데, 그것을 해결하려고 제가 setupFilesAfterEnv를 사용한 것입니다. jest.setup.ts 부분 참고 부탁드립니다.

이 방식을 사용할 경우 Jest 환경이 구축되고 테스트가 수행되기 전 단 `1회`만 수행합니다. 그렇기에 app 초기화는 한 번만 일어나고 테스트가 끝났을 때 app.close 또한 한 번만 일어납니다. beforeAll을 사용한 것도 그런 이유입니다.
테스트 수행 시간 그렇게 길지는 않습니다. 5초 가량? SWC 적용하면 더 빠르게도 돌릴 수 있습니다.
그렇기에 도메인 내에서 라우터 별로 분리해도 문제될 건 없을 것 같습니다.

값 검증 데코레이터는 Controller 계층에서 테스트가 불가능했습니다. 그래서 E2E에서 테스트를 하려고 했었습니다. 아마 한다면 명칭만 Controller 테스트라고 하고 결국 모듈들은 supertest를 하는 것이나 다름 없습니다.

데이터는 좀 과하게 들어갔네요. 이전 테스트 코드에서 만들어둔 예제 데이터를 복사 붙여넣기 하다가 5개 들어간 거 그대로 들어갔습니다 ㅎㅎ.. 2개만 있어도 되는 거 인정입니다.

주 메인 비즈니스 로직을 커버하는 줄은 50줄이면 충분하다는 건 공감합니다. 값 검증은 다음에 리팩토링 했을 때 혹여나 빼먹는 검증 데코레이터들이 있을까 싶어서 넣어놨습니다. 리팩토링 할 때 값 검증이 빠짐으로 인해 런타임 에러가 발생하는 건 꽤나 치명적이라 생각했습니다.

2024-11-26 18:04 UTC, Jo-Minseok commented on server/src/statistic/dto/statistic-query.dto.ts
> +  @IsInt({ message: '정수로 입력해주세요.' })
new ValidationPipe에서 transform: true로 해두면 입력 데이터의 유효성 검사를 하기 전에 데이터를 먼저 변환을 합니다. 그 후 검증 데코레이터들을 수행하기에 문제 없습니다.

2024-11-26 18:04 UTC, Jo-Minseok commented on server/src/statistic/dto/statistic-query.dto.ts
> +  @IsInt({ message: '정수로 입력해주세요.' })
new ValidationPipe에서 transform: true로 해두면 입력 데이터의 유효성 검사를 하기 전에 데이터를 먼저 변환을 합니다. 그 후 검증 데코레이터들을 수행하기에 문제 없습니다.

2024-11-26 18:30 UTC, asn6878 commented
> @asn6878 app을 initialize를 하고 실행 후 close 하는 과정이 6번 일어난다고 하셨는데, 그것을 해결하려고 제가 setupFilesAfterEnv를 사용한 것입니다. jest.setup.ts 부분 참고 부탁드립니다.
> 
> 이 방식을 사용할 경우 Jest 환경이 구축되고 테스트가 수행되기 전 단 1회만 수행합니다. 그렇기에 app 초기화는 한 번만 일어나고 테스트가 끝났을 때 app.close 또한 한 번만 일어납니다. beforeAll을 사용한 것도 그런 이유입니다.
테스트 수행 시간 그렇게 길지는 않습니다. 7~8초 가량의 수행 시간이 발생합니다. SWC 적용하면 더 빠르게도 돌릴 수 있습니다. docker 컨테이너를 사용한 테스트는 이것보다 스타트 시간이 더 길고 테스트 시간 또한 더 깁니다.

제가 완전히 `jest.setup.ts` 의 역할을 잘못 알고있었네요.
저는 단순히 app을 initialize하는 플로우를 단순히 묶어둔 것인줄 알았는데, 그게 아니라 `beforeAll()`로 테스트가 시작될 때 app 자체를 만들어두고 전역변수로 app을 재활용 하는것이네요. jest를 잘 몰랐는데, 공부하게 되는 계기가 되네요. 큰거 배워갑니다 🙇 

> 값 검증 데코레이터는 Controller 계층에서 테스트가 불가능했습니다. 그래서 E2E에서 테스트를 하려고 했었습니다. 아마 한다면 명칭만 Controller 테스트라고 하고 결국 모듈들은 supertest를 사용하는 것이나 다름 없습니다.

이 부분은 다시 설명을 드리면, Controller 계층을 가져와서 테스팅을 하려는것은 아니었습니다. 제가 드린 예제코드 처럼 단순히 **입력값 유효성 검증에 사용되는 dto클래스 자체를 import해서 `validate()` 함수를 통해 발생하는 응답값을 가지고 검증하면 supertest를 사용할 일이 없어요.** 다만 사용하게 된다면 네이밍은 Controller 테스트보다는 Dto 테스트가 적절하겠네요!

---

가장 근본이 되던 문제 (app initializing이 여러번 반복됨)가 해결되었으니, **각 라우터별로 테스트를 분리하면 validation 체킹도 e2e에서 함께 수행해도 별 문제가 되지 않을 것 같습니다. 좋은 방법인 것 같아요!**

앞으로 테스트는 라우터별로 파일 분리해서 작성하는것으로 알고 있겠습니다!

2024-11-26 18:32 UTC, Jo-Minseok commented
오 DTO 테스트라는 것도 있군요. 맞네요... dto 가져와서 validate하면 그만이군요...! 몰랐어요 ㅠ.ㅠ ㅋㅋ 값 검증 하는 부분을 따로 빼는 것도 좋을듯하네요. 메인 로직이랑 같은 파일에 있을 경우 메인 로직 테스트가 흐려지는 느낌이네요

2024-11-27 01:48 UTC, CodeVac513 approved these changes
수고 많으셨습니다.
저는 Jest에 대해서 엄청 모르고 있었네요.
성윤님께서 정리해준 대로 이해하고 작성할 수 있도록 하겠습니다.

2024-11-27 01:49 UTC, merged