✨ feat: 최신 게시글 실시간 업데이트 API 구현
boostcampwm-2024/web05-Denamu pull request #216
Opened 2024-11-26 13:03 UTC by CodeVac513

# 🔨 테스크
### Issue

-   close #203

### keys 이슈
- keys 명령이 실행되는 도중에는 Redis의 모든 명령을 블로킹합니다.
- 현재는 데이터가 몇 개 없어서 keys를 사용해도 큰 문제는 없지만 O(N)의 시간 복잡도라도 1만개, 10만개 등 늘어나면 성능 이슈가 발생할 수 있습니다.
- 추후에 성능 이슈가 발생한다면 `SCAN`으로 방법을 바꿀 수 있을 것 같습니다.
- 저는 SCAN을 사용하진 않았지만 `feed:recent`라는 key를 두어 recent 피드가 존재하는지 파악할 수 있도록 해놓았습니다.
- (PR을 작성하면서 생각해보니, 객체를 직렬화해서 List 하나에만 담아두는 것이 더 좋은 방법일 것 같습니다.)

### 소소한 이슈
- 처음에는 Redis 공식 문서에 있던 Node-redis를 사용했으나 Hash 데이터를 저장할 때 알 수 없는 에러가 발생했습니다.
- 혹시나 싶어 ioredis로 변경하니 기존 코드를 거의 수정하지 않고 에러 없이 사용할 수 있었습니다.
- 정보를 좀 더 찾아보니 Node-redis는 직렬화에 있어서 엄격한 편이고 ioredis는 유연하게 처리한다고 합니다.

### 피드에 추가적인 정보가 필요했습니다
- 처음에는 블로그에서 바로 가져온 데이터를 Redis에 저장하고 프론트에 전송할 생각이었습니다.
- 다만 이렇게 하면 blogPlatform 데이터나 author 데이터를 가져올 수 없는 문제가 생겼습니다.
- 그래서 DB에 저장되어던 가장 최근 피드의 ID를 구해서 새로 업데이트된 피드 ID를 계산했습니다.
- 피드를 저장하고 가지고 있던 ID를 활용해서 `rss_accept` 테이블과 JOIN 연산을 진행했습니다.
- 결과적으로 추가적인 데이터를 가져온 뒤 Redis에 저장할 수 있었습니다.

# 📋 작업 내용

- rss-notifier에서 최신 피드가 업데이트되면 Redis에 저장하는 로직 추가
- 업데이트된 피드가 없으면 캐싱된 데이터를 Redis에서 삭제
- `api/feed/recent`로 요청을 보내면 최신 피드 목록을 Redis에서 가져와 전송

# 📷 스크린 샷
![DB에 저장된 피드 목록](https://github.com/user-attachments/assets/3b839832-c4bf-4bc1-ae86-c7e34241af96)
- 데이터가 업데이트된 경우
![레디스에 저장된 새로운 피드 확인](https://github.com/user-attachments/assets/d41dc26c-c4f3-46d6-94c1-b6ef16c7c422)
![데이터가 있는 경우](https://github.com/user-attachments/assets/43f685ad-6989-4625-8531-12220d0118df)

---
- 업데이트가 없어서 데이터가 삭제된 경우
![새로 업데이트된 피드가 없을 경우 다 삭제](https://github.com/user-attachments/assets/273f236a-d749-4887-803e-60bc61d41708)
![데이터가 없을 경우](https://github.com/user-attachments/assets/24013fe0-dabe-4cb0-be0d-89cd8383a2d1)

---
- swagger
![스웨거 example](https://github.com/user-attachments/assets/9af9f631-5a47-4e1f-b292-ad907ac51888)

![스웨거 스키마](https://github.com/user-attachments/assets/1876ce31-2406-40c8-ae97-7e1663a36d47)

2024-11-27 17:23 UTC, Jo-Minseok requested changes
고생하셨습니다! 다음 주 리팩토링 주간 준비하려고 rss-notifier 코드 1번 라인부터 쭉 다 읽어봤습니다...! 예외가 발생할 사안들도 있고 코드상으로 이해 안 되는 부분들 리뷰 작성했습니다...! 한 줄 한 줄 처음부터 읽다보니 질문 사안들이 너무 많네요 ㅠㅠ

2024-11-27 17:23 UTC, Jo-Minseok commented on rss-notifier/src/rss-notifier.ts
>      rssObjects.map(async (rssObj) => {
P1) 120번 라인 등록된 RSS 피드가 없는게 아니라 등록된 RSS가 없는 것 같습니다! 뒤늦게 리뷰해서 죄송합니다...!

2024-11-27 17:23 UTC, Jo-Minseok commented on rss-notifier/src/db-access.ts
> +    if (redis) redis.disconnect();
P1) finally가 있는데 disconnect하는 이유는 뭔가요? disconnect가 오히려 Redis 서버와의 연결을 즉시 종료하는 거로 알고 있는데, 그럼 set이랑 del 같은 명령 수행하게 되면 순서 보장이 되나요? 제가 알기로는 비정상적으로 종료해서 비동기 작업이 있을 경우 문제가 발생하는 것으로 압니다.

2024-11-27 17:23 UTC, Jo-Minseok commented on rss-notifier/src/rss-notifier.ts
>    await insertFeeds(result);
P1) 지금은 삽입 하기 전에 마지막 값을 DB로부터 찾고 +1 을 더해서 시작 지점을 만드는 것 같은데, 그냥 insertFeeds 함수를 개조해서, 데이터 삽입 SQL을 execute할 때, 반환되는 객체에서 insertId를 얻고, successCount 수만큼 숫자를 빼면 데이터가 들어온 곳의 위치를 구할 수 있지 않을까요? 괜히 두 번 DB에 접근하는 낭비가 발생하는 것 같습니다. 단 Insert 1회로 접근이 가능할 것 같습니다!

2024-11-28 06:45 UTC, asn6878 commented on rss-notifier/src/db-access.ts
> +    if (redis) redis.disconnect();
음, 제 생각에는 catch 구문 안에 있다보니 이미 무엇인가 에러가 났을때 `disconnect` 중이라, 순서보장에 있어서 오류가 날 것 같지는 않다는 의견입니다만...!

finally의 quit()만 사용하는게 맞다는 것은 민석님과 동일한 의견입니다 ㅎㅎㅎㅎㅎ

2024-11-28 06:58 UTC, asn6878 approved these changes
어떻게보면 rss-notifier -> redis -> API Server 흐름으로 데이터가 왔다리 갔다리 하는 부분이라 실수하는 부분이 생길 수 있는데, 잘 해주셨네요!

대부분 중요한 문제들은 민석님이 언급해주셔서, 저는 몇가지 개선안들 살포시 놓고 가봅니다. 고생하셨어요 👍

2024-11-28 06:58 UTC, asn6878 commented on server/src/feed/feed.service.ts
> +        }
P3: 코드 가독성 관점에서, `if (keys.length <= 0)` 으로 잡는다면 빈 배열을 바로 return 해버리고, keys에 값들을 들고와 sorting을 하는등의 과정을 거칠 필요가 없어지지 않을까요?

2024-11-28 06:58 UTC, asn6878 commented on rss-notifier/src/db-access.ts
> +    }
P3: 현재는 새롭게 생성된 Feed의 수 만큼 Redis I/O가 발생중이기에 저번에 민석님이 사용하셨던 Redis pipeline 쓰면 불필요하게 반복되는 I/O를 줄일 수 있을 것 같아요.

```typescript
const pipeline = redis.pipeline();
for (const feed of resultList) {
  pipeline.hset(`feed:recent:${feed.id}`, feed);
}
pipeline.set("feed:recent", "true");
await pipeline.exec();
```

2024-11-28 08:17 UTC, Jo-Minseok commented on rss-notifier/src/db-access.ts
> +    }
오 이건 생각 못했는데 맞네요 이렇게도 처리할 수 있군요..!

2024-11-28 14:49 UTC, CodeVac513 commented on server/src/feed/feed.service.ts
> +        }
빈 배열 리턴 반영했습니다.
피드백 감사합니다. :)

2024-11-28 14:50 UTC, CodeVac513 commented on rss-notifier/src/db-access.ts
> +    }
성윤님 덕분에 pipeline 한 군데 더 써먹었습니다. 
감사합니다.

2024-11-28 14:50 UTC, CodeVac513 commented on rss-notifier/src/db-access.ts
> +      redis.del(...keys);
await 모두 붙여서 수정했습니다.
깜빡했네요.

2024-11-28 14:50 UTC, CodeVac513 commented on server/src/feed/feed.api-docs.ts
> +              {
반영했습니다.

2024-11-28 14:51 UTC, CodeVac513 commented on rss-notifier/src/db-access.ts
> +    redis.set("feed:recent", "true");
상수로 빼서 처리했습니다. :)

2024-11-28 14:52 UTC, CodeVac513 commented on rss-notifier/src/rss-notifier.ts
> +        `[${idx}번째 rss [${rssObj.rssUrl}] 에서 데이터 조회하는 중...`,
반영했습니다!

2024-11-28 14:52 UTC, CodeVac513 commented on rss-notifier/src/rss-notifier.ts
>      rssObjects.map(async (rssObj) => {
여기도 반영했습니다.

2024-11-28 14:52 UTC, CodeVac513 commented on server/src/feed/feed.api-docs.ts
> +      examples: {
반영했습니다.

2024-11-28 14:53 UTC, CodeVac513 commented on rss-notifier/src/db-access.ts
> +    if (redis) redis.disconnect();
quit만 사용하는 것으로 반영했습니다.

2024-11-28 14:53 UTC, CodeVac513 commented on rss-notifier/src/rss-notifier.ts
>    await insertFeeds(result);
insertFeeds 를 개조해서 getRecentFeedStartId 함수를 삭제했습니다.
좋은 의견 감사합니다. :)

2024-11-28 15:14 UTC, Jo-Minseok requested changes
반영해주세요.

2024-11-28 15:14 UTC, Jo-Minseok commented on rss-notifier/src/rss-notifier.ts
> +  console.log(recentFeedStartId);
P1) 콘솔 로그 뭐죠..?

2024-11-29 17:30 UTC, Jo-Minseok approved these changes
고생하셨습니다! 피드백이 정말 고봉밥 of 고봉밥이었을텐데, 적용해주시느라 고생 많으셨습니다.

2024-11-30 09:02 UTC, merged