✅ test: Rss 전체 조회,  승인, 거절 및 검색 API 테스트 코드 작성
boostcampwm-2024/web05-Denamu pull request #224
Opened 2024-11-27 11:02 UTC by asn6878

# 🔨 테스크
### Issue
- #13
- #61 
- #62

# 📋 작업 내용
### 각 로직별 테스트 코드 작성
given, when, then 패턴을 활용해 가시성있는 테스트 작성을 시도해 보았습니다.
또한, 테스트와 무관한 불필요한 로직들은 최대한 줄이려 노력했습니다.

### Entity Fixture 작성
특정 엔티티를 테스트 환경에서 더욱 짧고 간편하게 다룰 수 있는 Fixture를 작성해두었습니다.
앞으로 다른 엔티티에도 사용할 일 이생기면 `EntityFixture.createEntityFixture();` 의 형태로 생성할 수 있도록 만들어 사용하면 테스트코드의 가독성이 훨씬 좋아질 것 같아요. 😄 

### dto <-> entity 간 매핑을 위한 편의 클래스
`from`과 `of` 패턴을 적절히 활용해 테스트간 검증을 위해 변환이 필요한 과정을 단순화 하였습니다.
`from, of`의 메서드명이 헷갈리시는 분들은 [정적 팩토리 메서드 패턴](https://inpa.tistory.com/entry/GOF-%F0%9F%92%A0-%EC%A0%95%EC%A0%81-%ED%8C%A9%ED%86%A0%EB%A6%AC-%EB%A9%94%EC%84%9C%EB%93%9C-%EC%83%9D%EC%84%B1%EC%9E%90-%EB%8C%80%EC%8B%A0-%EC%82%AC%EC%9A%A9%ED%95%98%EC%9E%90)에서 of와 from 메서드가 가지는 의미가 무엇인지 보고 오시면 됩니다!

# 📷 스크린 샷(선택 사항)

2024-11-28 08:08 UTC, Jo-Minseok requested changes
고생하셨습니다! 코드상 실수하신 부분 체크해뒀으니 확인 부탁드립니다. File Change가 상당히 많군요 ㅠㅠㅋㅋ  Fixture를 사용하는 건 공감이 가나, of와 from을 이 코드들에서 왜 사용하는지는 잘 모르겠습니다... 생성자를 대체하기 위함이라 보는데, 저희는 생성자를 여러개 두는 것도 아니라 하나만 두는건데 괜히 헷갈리는 느낌이군요... 생성에서의 로직이 있는 것도 아니라 불편한 듯합니다. 혹시 이렇게 했을 때의 이점이 있는걸까요?

2024-11-28 08:08 UTC, Jo-Minseok commented on server/test/rss/rss.e2e-spec.ts
> +        const requestDto = RssRegisterDto.from(RssFixture.createRssFixture());
P5) RssFixture를 사용하는 건 이해했습니다. 하지만 createRssFixture를 썼을 때, 그냥 바로 {blog: 'blog', name: 'name', email: 'test@test.com', rssUrl: 'https://example.com/rss' }로 반환하면 안 되나요? from을 거쳐서 들어가는 게 뭔가 어색한 것 같은데, 이렇게 했을 때 장점은 무엇인가요?

2024-11-28 09:01 UTC, CodeVac513 reviewed
이미 민석님이 엄청 자세하게 봐주셨네요.
중간에 민석님이 놓친 사소한 것들만 남았더라구요.
수고 많으셨습니다!

2024-11-28 09:01 UTC, CodeVac513 commented on server/test/rss/reject.e2e-spec.ts
> +      });
P4) 민석님이 위에 리뷰 남겨주신 것처럼 이것도 DTO 테스트의 일환이라고 생각되네요.
혹시 민석님 의견을 반영하신다면 이 부분도 체크를 한 번 해야할 것 같아서 표시용으로 코멘트 달아놓을게요.

2024-11-28 09:04 UTC, Jo-Minseok commented on server/test/feed/fixture/feedFixture.ts
> +  static customFeedFixture(
성윤님 추가 피드백 드려 죄송합니다! 만약 게시글 같은 경우 저희는 순서를 중요시 여기다 보니 createdAt도 받을 수 있게 해야할 것 같습니다...!

2024-11-28 09:07 UTC, CodeVac513 commented on server/test/rss/accept.e2e-spec.ts
> +        expect(noSessionResponse.status).toBe(401);
쿠키가 없을 때랑 세션이 없을 때, 두 가지가 한 테스트에 있긴 하네요.
명확하게 분리하는 것도 좋을 것 같습니다.

2024-11-28 11:57 UTC, asn6878 commented on server/test/rss/accept.e2e-spec.ts
> +    await rssRepository.query('DELETE FROM rss');
TypeORM 메서드 활용할 수 있도록 반영 처리 완료했습니다!

2024-11-28 12:00 UTC, asn6878 commented on server/test/rss/accept.e2e-spec.ts
> +  afterAll(async () => {
반영했습니다~

2024-11-28 12:04 UTC, asn6878 commented on server/test/rss/accept.e2e-spec.ts
> +      });
해당 코드는 별도로 dto를 사용하지 않고, Controller 계층의 매개변수로 바로 받고있었던터라, DTO를 직접 import 해와 class-validator를 검증하는 유닛테스트를 작성하기 어렵다고 생각했어요.

코드자체를 DTO로 받아오도록 변경하고, 일관성있게 DTO 테스트로 분리할까요?

2024-11-28 12:05 UTC, asn6878 commented on server/test/rss/fixture/rssAcceptFixture.ts
> +}
음, 이것도 createCustomAcceptFixture를 만들 수 있을 것 같은데. 이건 무성님이 사용하신 방법이 더 좋은것 같더라구요.

Partials 사용하는 형태로 변경하겠습니다.

2024-11-28 12:05 UTC, asn6878 commented on server/test/rss/reject.e2e-spec.ts
> +  });
처리했습니다~

2024-11-28 12:06 UTC, asn6878 commented on server/test/rss/reject.e2e-spec.ts
> +    await redisService.redisClient.set('auth:sid', 'test_admin');
처리 했습니다~

2024-11-28 12:14 UTC, asn6878 commented on server/test/rss/fixture/rssFixture.ts
> +    return new Rss(this.GENERAL_RSS);
순수 객체 리터럴을 사용할 것이냐 VS 실제 Entity 인스턴스를 사용할 것이냐 의 관점인 것 같은데요.

1. 실제 Entity 인스턴스에 구현가능한 편의 클래스를 추후 활용할 수 있음.
2. 타입검사가 가능함.
3. 객체 리터럴도 TypeORM에 넣을 수는 있지만 조금더 실제 실행 환경과 근접해 신뢰성있는 테스트를 할수있다. (근데, 그냥 객체리터럴이랑 엔티티랑 정확하게 무슨차이가 있는지까지는 잘 모르겠네요 ㅠㅠ)

위와 같은 이유들로 엔티티 타입으로 변환한 다음 사용하려고 노력했어요.

2024-11-28 12:16 UTC, Jo-Minseok commented on server/test/rss/accept.e2e-spec.ts
> +      });
저는 한다면 일관성 있게 하는 게 맞지 않나 싶습니다.

2024-11-28 12:19 UTC, asn6878 commented on server/test/rss/rss.e2e-spec.ts
> +        const requestDto = RssRegisterDto.from(RssFixture.createRssFixture());
from을 거치는 부분은, 엔티티를 RssRegisterDto로 변환하기 위함입니다. 

`of`와 `from` 패턴을 활용한 DTO <-> Entity 간의 매핑을 도와주기 위해 DTO 클래스에 정적 편의 매서드를 적용한 사례이구요.

이러한 DTO <-> Entity 간 매핑은 테스트뿐만 아니라 추후 비즈니스 로직을 작성할 때도 사용될 수 있다고 생각해 활용했습니다.

2024-11-28 12:21 UTC, asn6878 commented on server/test/feed/fixture/feedFixture.ts
> +  static customFeedFixture(
이 부분도 아까 말씀드린 무성님이 활용하신 방법으로 Fixture를 수정하겠습니다!

2024-11-28 12:26 UTC, Jo-Minseok commented on server/test/rss/rss.e2e-spec.ts
> +        const requestDto = RssRegisterDto.from(RssFixture.createRssFixture());
아하 비즈니스 로직에서도 사용이 되군요

2024-11-28 17:26 UTC, asn6878 commented on server/test/rss/reject.e2e-spec.ts
> +      });
DTO 테스트로 분리 완료하였습니다!

2024-11-28 17:26 UTC, asn6878 commented on server/test/rss/fixture/rssAcceptFixture.ts
> +}
모든 픽스쳐에서, 필요한 필드만을 `Partial`을 활용해 추가할 수 있도록 처리 완료하였습니다!

2024-11-28 17:50 UTC, CodeVac513 reviewed
수고 많으셨습니다!
잘 작성해주셔서 DTO 테스트 잘 참고하겠습니다. :)
질문 하나 있는데, 그거만 확인되면 승인할게요.

2024-11-28 17:50 UTC, CodeVac513 commented on server/src/rss/rss.entity.ts
> +
P3) 혹시 이 생성자 사용하는 데가 있나요?
코드를 살펴봤는데 사용하는 곳이 없는 것 같아서 여쭤봅니다.

2024-11-28 18:36 UTC, asn6878 commented on server/src/rss/rss.entity.ts
> +
오잉? 다 제거한줄 알았는데, 삭제를 덜했군요.
싹다 제거 완료했습니다!

2024-11-28 18:38 UTC, CodeVac513 approved these changes
LGTM!

2024-11-29 14:28 UTC, Jo-Minseok approved these changes
아주 뜨거운 토론을 했던 테스트 셋팅이었군요 ㅠㅠㅋㅋ 이번 경험을 통해서 테스트 description, 범위, 픽스처 방법에 대해서도 미리 정의해야 한다는 사실을 알게 되었습니다! 그리고 멘토님께서 TS를 왜 쓰는가에 대해 말씀을 해주셨는데 성윤님께서 말씀해주셨던 것들에 전부 공감할 수 있었습니다! 아주 큰 거 배워갑니다!

2024-11-30 08:29 UTC, merged