✨ feat: 블로그 플랫폼별 통계 API 구현
boostcampwm-2024/web05-Denamu pull request #225
Opened 2024-11-27 14:28 UTC by Jo-Minseok

# 🔨 테스크

### Issue

-   close #205

### 쿠키를 통한 관리자 권한 확인 테스트 위치

-   E2E는 아니라고 생각했는데, 그렇다고 DTO는 더욱 더 아닌 것 같아서 권한 테스트는 E2E에서 하는 것으로 생각했다.
- 하지만... 권한은 정작 필요없는 API 였다는... ㅠㅠ 이거 때문에 로그인 취약점 알았던건데...

# 📋 작업 내용

-   통계 API 관리자 권한 -> 일반 사용자들도 사용 가능하게 변경
-  관리자 권한 테스트 코드 제거
- 블로그별 통계 API 테스트 코드 작성
- 블로그별 통계 API 구현

# 📷 스크린 샷(선택 사항)

동작 화면 첨부

2024-11-27 18:00 UTC, CodeVac513 approved these changes
수고많으셨습니다!
통계 API 끼리 로직이 비슷한 감이 있네요. 비슷비슷해서 금방 읽히는 것 같아요.

2024-11-28 05:55 UTC, asn6878 requested changes
몇가지 고려할만한 사항 남겨두었습니다.
고생하셨어요~ 👍

2024-11-28 05:55 UTC, asn6878 commented on server/src/statistic/statistic.service.ts
> +  }
P2: **저희는 커스텀 레포지토리를 반드시 사용하기로 했기 때문에** 이러한 DAO 계층을 담당하는 부분은 `RssAcceptRepository` 안의 메서드로 선언되어야 하지 않을까요?

저도 이전에 서비스에서 쿼리빌더 막 썼는데, 지금 생각해보니 커스텀 레포지토리 쓸거면 레포지토리 안에 구현해두고 가져다가 사용하는게 더 맞는 방법 아닌가...? 라는 생각이 들었어요.

민석님 생각은 어떠세요?

2024-11-28 05:55 UTC, asn6878 commented on server/test/statistic/all.e2e-spec.ts
> +      redisService.redisClient.set('auth:test1234', 'test'),
P3: Repository 의존성 가져오는 부분, rssAccept 만드는 부분은 Fixture로 변경할 수 있을 것 같습니다.
만약 다양한 형태의 Fixture가 필요하다면 `CreateCustomFixture...` 형태로 변경하고자 하는 인자들을 파라미터로 만들어 반환하는 방법도 좋아요!
다만, 커스텀픽스쳐까지 만드는게 부담스러우시다면 그냥 object 형태로 사용해도 나쁘지 않다고 봅니다.

2024-11-28 05:55 UTC, asn6878 commented on server/test/statistic/platform.e2e-spec.ts
> +    );
아까 말한 커스텀 픽스처가 사용되기 좋은 예제네요. 함수에 파라미터로 Partial을 전달받아 이런식으로 변경이 필요한 속성(userName, blogPlatform, rssUrl...)들만 바꿔 엔티티를 반환해주면 라인수를 훨씬 줄이고 가독성도 높일 수 있을 것 같아요.

2024-11-28 07:16 UTC, Jo-Minseok commented on server/src/statistic/statistic.service.ts
> +  }
오 좋습니다! 그렇네요 쿼리 빌더 수행해놓은 함수들을 묶어서 레포지토리 안에 하나의 함수로 만들어두면 되겠네요! 좋은 피드백 감사합니다

2024-11-28 17:29 UTC, asn6878 commented on server/test/statistic/platform.e2e-spec.ts
> +    );
이부분은 역으로 민석님 피드백 반영하다가, Partials를 활용하는 방식으로 바뀌었네요 ㅋㅋㅋㅋㅋ
이제는 필요한 필드만 추가적으로 넣어서 사용해주시면 됩니다~~

2024-11-30 08:31 UTC, merged