✅ test:  admin 로그인, admin 회원가입, sessionId 확인 API 테스트 코드 작성
boostcampwm-2024/web05-Denamu pull request #228
Opened 2024-11-28 08:21 UTC by CodeVac513

# 🔨 테스크

### Issue

-   close  #57
- close  #58
- close  #193 

# 📋 작업 내용
- admin(관리자) 로그인 API 테스트 코드 작성

- admin 회원가입 API 테스트 코드 작성

- sessionId 확인 API 작성
- loginRepository -> adminRepository로 변수명 수정했습니다.

2024-11-30 11:45 UTC, Jo-Minseok requested changes
고생하셨습니다! 성윤님과 함께 의논해볼 테스트와 관련된 논의 거리를 달아놨습니다. 확인하고 답변 부탁드립니다.

2024-11-30 11:45 UTC, Jo-Minseok commented on server/test/admin/admin.e2e-spec.ts
> +        expect(response.body.message).toBe('정상적인 sessionId 입니다.');
P2) 이렇게 message만 비교하는 것 보다는 toStrictEqual로 객체 비교를 하는 건 어떤가요?
이렇게 toStrictEqual 방식으로 했을 때는 장점이 있습니다.
1. 저희가 예상하지 못 한 값이 응답에 포함되는 경우에 대해서도 테스트를 할 수 있습니다. 어느 엔티티에서 특정 속성만 추출하여 데이터를 응답해야 하는 경우 실수로 엔티티에 있는 속성을 포함해버릴 수 있습니다. 이런 실수를 방지할 수 있습니다.
2. 단 한번의 expect만 수행하면 됩니다. 지금 속성을 다 비교하는 방식에서는 속성 하나가 추가되면 매번 expect를 작성해야 하는 불편함이 존재합니다.
3. 테스트 코드 길이가 줄어듭니다. expect에서 하나 하나 검사하는 것 보다 한 번에 처리하기에 expect나 객체 속성 이름을 여러번 적지 않아도 됩니다.

장점이 있다면 단점도 있습니다.
1. 가독성이 떨어집니다. 어떤 속성을 비교하는 지 확실히 알 수 없습니다.
2. 테스트의 expect 데이터와 속성 순서도 일치해야 합니다.

저는 이 장단점에서 '예상치 못 한 데이터가 응답에 포함되는 경우에 대해서도 테스트 할 수 있다.'는 점이 가장 메리트 있다고 생각합니다.
그렇다고 response 응답 객체 전체를 비교하기는 어려우니 Status. Code랑 body 전체 정도만 비교하은 건 어떤가요?-?

성윤님도 함께 언급해서 이야기 나눠봤으면 좋겠네요!
@asn6878

2024-11-30 11:45 UTC, Jo-Minseok commented on server/test/feed/feed.e2e-spec.ts
> +        expect(response.body.data.result).toHaveLength(5);
P1) 데이터의 길이만을 비교하는 건 문제가 있을듯 합니다. 저희 피드 제공 기능의 핵심은 '최신 게시글부터 제공되어야 한다는 점'이라고 생각합니다. 그렇다면 데이터가 실제적으로 최신 게시글부터 나오는지를 확인할 필요성이 있을 것 같습니다.

2024-12-01 08:42 UTC, asn6878 approved these changes
전체적으로 성공 응답의 message 자체는 Assert 할 필요가 없다고 생각합니다만, 굳이 뺄필요도 없다고 생각하긴 해요!
민석님이 좋은 논의거리를 만들어주셔서 그부분 의사결정만 진행되고나면, 처리해도 좋을 것 같아요 😄 

고생하셨습니다~

2024-12-01 10:51 UTC, Jo-Minseok commented
@asn6878 답변 감사합니다.
message라는 속성이 API를 사용하는 곳에서 활용이 안 된다면 테스트에서 빼는 건 저도 동의합니다.

제가 생각했던 것은 API 응답에서 message 를 Body에 포함한 응답을 했을 때, 이 message 속성을 FE에서 클라이언트에게 보여주는 용도로 사용이 된다면 의도하지 않은 다른 메세지로 보낼 수 있지 않을까? 라는 생각입니다.
또한 서버에서 발생한 오류에 대해서 API 명세서를 적은 이유가 프론트엔드와 백엔드 간의 통신 데이터를 맞추자는 목적으로 작성된 것으로 알고 있습니다. 그렇다면 API 명세에 따라 테스트 코드를 작성을 해서 API 명세와 정확히 일치한 데이터를 보내는 지 확인을 해서 각 분야끼리의 소통 비용을 최소화하는 것이 필요하다고 생각했습니다.
이번 프로젝트 할 때, 백엔드가 API 명세서를 다 적어두고 실제로 데이터는 잘 못 보내는 경우가 꽤 있었어서 프론트분들과 필요하지 않은 소통을 하는 경우가 있었다 보니 테스트 코드를 작성 후에 개발을 했다면 이런 소통 비용을 줄였지 않았을까 하는 생각이었습니다.

성윤님께서 말씀해주신 "특정 비즈니스 로직이 통제된 조건 안에서 의도한 응답을 반환하는가?"라는 문장에서 "의도한 응답을 반환하는가?" 에 초점을 맞춘다면 의도하지 않은 데이터를 함께 반환하는 것은 "의도한 응답을 반환하지 않은 것"이라고 생각합니다. 그래서 추가적인 데이터 전송에 대해 민감했던 것 같습니다. 

"비즈니스 로직을 작성할때부터 아예 치명적인 실수"를 감지하는 것 또한 테스트 코드의 목적이라고 생각합니다
 이번에 저는 API를 구현하면서 응답 DTO를 사용하지 않았었습니다. DB에서 데이터를 추출한 데이터로 응답을 한다고 가정하면, 단순 DB에서 추출한 데이터를 바로 응답하게 했었는데, 여태 응답 DTO에 대한 아무런 피드백이 없어서 이런 식으로 개발을 했었습니다. 성윤님 같은 경우 응답 DTO를 사용하신 것 같더라고요. API를 제작하는 배경 지식의 차이에서 발생한 논제라고 생각이 되네요.

저도 테스트 코드 자체는 간단하게 적는 것이 좋다고 생각합니다. 테스트 코드도 유지 보수가 되어야 하는 타겟이기 때문입니다.

전 개발 경험이 부족해서 최대한 API 명세서와 동일하게 맞춰서 확실하게 검증하다 보니 테스트 코드에 API 명세서를 그대로 녹여내는 경우가 많았습니다. 그리고 테스트 처음을 TDD로 시작했어서 그런지 테스트 코드를 엄청 자세하게 짜두고 API를 이 테스트에 맞게 작성을 했는가 검증하는 용도로 썼다 보니 더 그런 것 같네요.
또한, 제 자신을 믿을 수 없어서 의도하지 않은 데이터를 응답에 포함하거나 다른 속성 이름으로 응답하는 경우가 있었다 보니 테스트 코드를 확실히 짜고, 응답 데이터 또한 검증하여야 된다고 생각했는데, 응답 DTO를 사용했다면 이런 문제가 발생하지 않았을 거라고 배웠습니다. 앞으로 응답 DTO 잘 사용해야겠네요. 귀찮아서 테스트 코드에서 그냥 응답을 검증하는 경우가 많았는데, DTO를 사용하면 이 비용이 줄 것 같다고 느꼈습니다. 

항상 마스터님들께서 '테스트 코드는 리팩토링을 할 때의 안전 장치 같은 것'이라는 말씀에 꽂혔어서 그럼 안전장치라면 자세할 수록 견고한 안전장치가 아닐까? 라는 생각에 사로잡혀 있었던 것 같습니다.

결론적으로, message를 빼는 것은 동의를 하나, 
```typescript
        expect(response.body.data.result).toHaveLength(5);
```
이런 식으로 추상적으로 테스트를 수행하는 건 같이 작업하는 사람이나 추후에 저희 작업을 혹여나 물려 받을 사람이 있을 경우 문제가 생긴다고 생각하는 건 여전합니다. 테스트 또한 커뮤니케이션 수단으로 사용되는데, 이 테스트를 보고 어떠한 데이터에 대한 테스트를 하는 것인지 전혀 감이 안 잡히는 코드라고 생각이 듭니다. 그리고 이 API가 어떤 데이터를 응답하는지 감도 안 잡히는 상황입니다. 그래서 statusCode와 Body에서도 Data만을 검증하고 message 같은 정적인 응답에 대해서는 검증하지 않는 건 어떠신가여?

2024-12-01 10:52 UTC, Jo-Minseok commented on server/test/admin/admin.e2e-spec.ts
> +        expect(response.body.message).toBe('정상적인 sessionId 입니다.');
@asn6878 답변 감사합니다.
message라는 속성이 API를 사용하는 곳에서 활용이 안 된다면 테스트에서 빼는 건 저도 동의합니다.

제가 생각했던 것은 API 응답에서 message 를 Body에 포함한 응답을 했을 때, 이 message 속성을 FE에서 클라이언트에게 보여주는 용도로 사용이 된다면 의도하지 않은 다른 메세지로 보낼 수 있지 않을까? 라는 생각입니다.
또한 서버에서 발생한 오류에 대해서 API 명세서를 적은 이유가 프론트엔드와 백엔드 간의 통신 데이터를 맞추자는 목적으로 작성된 것으로 알고 있습니다. 그렇다면 API 명세에 따라 테스트 코드를 작성을 해서 API 명세와 정확히 일치한 데이터를 보내는 지 확인을 해서 각 분야끼리의 소통 비용을 최소화하는 것이 필요하다고 생각했습니다.
이번 프로젝트 할 때, 백엔드가 API 명세서를 다 적어두고 실제로 데이터는 잘 못 보내는 경우가 꽤 있었어서 프론트분들과 필요하지 않은 소통을 하는 경우가 있었다 보니 테스트 코드를 작성 후에 개발을 했다면 이런 소통 비용을 줄였지 않았을까 하는 생각이었습니다.

성윤님께서 말씀해주신 "특정 비즈니스 로직이 통제된 조건 안에서 의도한 응답을 반환하는가?"라는 문장에서 "의도한 응답을 반환하는가?" 에 초점을 맞춘다면 의도하지 않은 데이터를 함께 반환하는 것은 "의도한 응답을 반환하지 않은 것"이라고 생각합니다. 그래서 추가적인 데이터 전송에 대해 민감했던 것 같습니다. 

"비즈니스 로직을 작성할때부터 아예 치명적인 실수"를 감지하는 것 또한 테스트 코드의 목적이라고 생각합니다
 이번에 저는 API를 구현하면서 응답 DTO를 사용하지 않았었습니다. DB에서 데이터를 추출한 데이터로 응답을 한다고 가정하면, 단순 DB에서 추출한 데이터를 바로 응답하게 했었는데, 여태 응답 DTO에 대한 아무런 피드백이 없어서 이런 식으로 개발을 했었습니다. 성윤님 같은 경우 응답 DTO를 사용하신 것 같더라고요. API를 제작하는 배경 지식의 차이에서 발생한 논제라고 생각이 되네요.

저도 테스트 코드 자체는 간단하게 적는 것이 좋다고 생각합니다. 테스트 코드도 유지 보수가 되어야 하는 타겟이기 때문입니다.

전 개발 경험이 부족해서 최대한 API 명세서와 동일하게 맞춰서 확실하게 검증하다 보니 테스트 코드에 API 명세서를 그대로 녹여내는 경우가 많았습니다. 그리고 테스트 처음을 TDD로 시작했어서 그런지 테스트 코드를 엄청 자세하게 짜두고 API를 이 테스트에 맞게 작성을 했는가 검증하는 용도로 썼다 보니 더 그런 것 같네요.
또한, 제 자신을 믿을 수 없어서 의도하지 않은 데이터를 응답에 포함하거나 다른 속성 이름으로 응답하는 경우가 있었다 보니 테스트 코드를 확실히 짜고, 응답 데이터 또한 검증하여야 된다고 생각했는데, 응답 DTO를 사용했다면 이런 문제가 발생하지 않았을 거라고 배웠습니다. 앞으로 응답 DTO 잘 사용해야겠네요. 귀찮아서 테스트 코드에서 그냥 응답을 검증하는 경우가 많았는데, DTO를 사용하면 이 비용이 줄 것 같다고 느꼈습니다. 

항상 마스터님들께서 '테스트 코드는 리팩토링을 할 때의 안전 장치 같은 것'이라는 말씀에 꽂혔어서 그럼 안전장치라면 자세할 수록 견고한 안전장치가 아닐까? 라는 생각에 사로잡혀 있었던 것 같습니다.

결론적으로, message를 빼는 것은 동의를 하나, 
```typescript
        expect(response.body.data.result).toHaveLength(5);
```
이런 식으로 추상적으로 테스트를 수행하는 건 같이 작업하는 사람이나 추후에 저희 작업을 혹여나 물려 받을 사람이 있을 경우 문제가 생긴다고 생각하는 건 여전합니다. 테스트 또한 커뮤니케이션 수단으로 사용되는데, 이 테스트를 보고 어떠한 데이터에 대한 테스트를 하는 것인지 전혀 감이 안 잡히는 코드라고 생각이 듭니다. 그리고 이 API가 어떤 데이터를 응답하는지 감도 안 잡히는 상황입니다. 그래서 statusCode와 Body에서도 Data만을 검증하고 message 같은 정적인 응답에 대해서는 검증하지 않는 건 어떠신가여?

2024-12-02 15:46 UTC, CodeVac513 commented on server/test/admin/admin.e2e-spec.ts
> +        expect(response.body.message).toBe('정상적인 sessionId 입니다.');
두 분이 앞서서 많은 이야기를 해주셔서 답글을 다는데 오래 걸렸네요.
미리 게더에서 제 의견을 말씀드리기도 했지만 휘발될 수 있어서 여기에 한 번 더 남기겠습니다.
먼저 결론부터 말씀 드리면 저는 성윤님 입장에 좀 더 가깝습니다.

사실 저는 테스트 경험이 많지 않아 오히려 두 분 코드를 보고 배워가는 입장입니다. 
그래서 현업에서 개발하고 있는 친구들 찬스를 썼는데요, 하나 같이 하는 말이 `어디까지 데이터를 받았을 때 정상인가`를 생각하고 설정하라는 말을 해주더라고요.
예시)
status가 200이어야 하는데 400이 넘어온다 -> 정상인 상태가 아님.
status가 200이고 메세지가 '완료'로 넘어와야 하는데, 200에 '성공' 으로 넘어온다. -> 비즈니스 로직을 깨지 않는 정상의 범주라 생각할 수 있음.

평소에 이런 생각을 잘 안 했었는데, 여러분 덕분에 시야도 넓어지고 생각을 많이 할 수 있는 기회가 생겼네요.
감사합니다.

2024-12-03 17:01 UTC, Jo-Minseok approved these changes

2024-12-03 17:02 UTC, merged