♻️ refactor: admin, statistic 리팩토링
boostcampwm-2024/web05-Denamu pull request #269
Opened 2024-12-03 02:01 UTC by asn6878

### Issue

- #260 
- #259 

# 📋 작업 내용
- admin, statistic DAO 계층 분리.
전에 이야기 나왔던대로, `findOne` 같은 메소드들도 repository에서 커스텀화 해 사용할 수 있도록 수정하였습니다.

- admin, statistic Swagger 어노테이션 정의 분리
마찬가지로, 컨벤션에 맞추어 어노테이션을 API 별로 분리하였습니다.

- admin, statistic Controller, Service Layer 메서드명 컨벤션
각 레어의 메서드명들을 컨벤션에 맞게 수정하였습니다.

# 📷 스크린 샷(선택 사항)
모든 테스트 정상 동작 됨을 확인 하였습니다.
![image](https://github.com/user-attachments/assets/3b72eb21-4017-4c9c-a7c1-454452a5ef1e)

2024-12-03 11:35 UTC, CodeVac513 reviewed
LGTM!
질문 하나 남겼습니다. 그거만 해결되면 저는 잘 해주신 것 같아요.

2024-12-03 11:35 UTC, CodeVac513 commented on server/src/admin/admin.controller.ts
>    }
P3) get 대신 read로 사용하는 거 아니었나요?

2024-12-03 16:32 UTC, Jo-Minseok requested changes
고생하셨습니다! 이미 컨벤션에 대해서는 무성님께서 잡아주셔서 저는 볼게 없네요.
회의에서 나온 Repository 자체 findOne, find 함수에서 where 속성만 있으면 따로 함수 분리는 하지 말자는 이야기에 따라 바꿔주시기만 하면 됩니다!

2024-12-05 05:29 UTC, asn6878 commented on server/src/admin/admin.controller.ts
>    }
처리 완료했습니다~

2024-12-05 05:30 UTC, asn6878 commented
> 고생하셨습니다! 이미 컨벤션에 대해서는 무성님께서 잡아주셔서 저는 볼게 없네요. 회의에서 나온 Repository 자체 findOne, find 함수에서 where 속성만 있으면 따로 함수 분리는 하지 말자는 이야기에 따라 바꿔주시기만 하면 됩니다!

복구 처리 완료했습니다. 확인해주세요~

2024-12-05 06:22 UTC, Jo-Minseok approved these changes
고생하셨습니다!

2024-12-05 06:32 UTC, CodeVac513 approved these changes
LGTM!

2024-12-05 13:01 UTC, merged